router:
  model_ttl: 30
  router_heartbeat_interval_seconds: 15
  use_task_classification: true
  router_log_file: "/data/db/"
  router_logging_level: "info"
  query_timeout: 60.0

trainer:
  training_interval_threshold_seconds: 10
  training_batch_size: 10
  normalizer: "mean"
  reward_output_quality_weight: 1.0
  reward_response_time_weight: 1.0
  reward_energy_consumption_weight: 0.5
  bounds_file_path: "/config/bounds.yml"
  dummy_output_quality: true

database:
  file_path: "/data/db/"
  file_name: "metrics-{{ROUTER_ID}}.duckdb"

routing:
  algorithm: "mlp"
  model_path: null
  model_save_dir: "/data/mab"
  training_data_path: "/data/routerbench/training_data.pkl"
  embedding_model: "all-MiniLM-L12-v2" 
  
  mab:
    mab_options: "--epsilon 0.1"
  
  heuristic:
    heuristic_epsilon: 0.1
  
  knn:
    n_neighbors: 50
    distance_metric: "cosine"
    leaf_size: 30
  
  mlp:
    hidden_layer_sizes: [100, 100, 100]
    activation_function: "relu"
    learning_rate_method: "constant"
    learning_rate: 0.001
  
taskClassifier:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  dataset_path: "/data/hf_datasets/"
  temperature: 0.1