jetstream {}

cluster: {
    name: tacc,
    port:6222,
    routes: [
        "nats://nats-tacc:6222"
    ]
}

gateway: {
    name: tacc,
    port: 7222,
    gateways: [
        { name: uc, url: "nats://nats-uc:7222"},
        { name: tacc, url: "nats://nats-tacc:7222"},
        { name: edge, url: "nats://nats-edge:7222"},
    ]
}